/**
 * Curated Word Database for Imposter Game (250+ High Clueability Words)
 * Filtered for universal recognizability, zero offensive terms, and high party engagement.
 */

import type { WordItem, CategoryMeta } from '../types/word';

export const CATEGORIES_META: CategoryMeta[] = [
  { id: 'random', nameKey: 'categories.random', icon: '🎲', descriptionKey: 'categories.randomDesc', wordCount: 250 },
  { id: 'everyday', nameKey: 'categories.everyday', icon: '☕', descriptionKey: 'categories.everydayDesc', wordCount: 50 },
  { id: 'food', nameKey: 'categories.food', icon: '🍕', descriptionKey: 'categories.foodDesc', wordCount: 50 },
  { id: 'animals', nameKey: 'categories.animals', icon: '🦁', descriptionKey: 'categories.animalsDesc', wordCount: 40 },
  { id: 'movies', nameKey: 'categories.movies', icon: '🎬', descriptionKey: 'categories.moviesDesc', wordCount: 40 },
  { id: 'places', nameKey: 'categories.places', icon: '🗼', descriptionKey: 'categories.placesDesc', wordCount: 40 },
  { id: 'tech', nameKey: 'categories.tech', icon: '💻', descriptionKey: 'categories.techDesc', wordCount: 30 },
];

export const SEED_WORDS: WordItem[] = [
  // --- 1. Food & Drink (50 words) ---
  { id: 'pizza', word: 'Pizza', category: 'food', difficulty: 'easy', language: 'en', clueability: 10, popularity: 10 },
  { id: 'sushi', word: 'Sushi', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'burger', word: 'Hamburger', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'tacos', word: 'Tacos', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'pancakes', word: 'Pancakes', category: 'food', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'ice_cream', word: 'Ice Cream', category: 'food', difficulty: 'easy', language: 'en', clueability: 10, popularity: 10 },
  { id: 'coffee', word: 'Coffee', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'tea', word: 'Green Tea', category: 'food', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'chocolate', word: 'Chocolate', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'spaghetti', word: 'Spaghetti', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'popcorn', word: 'Popcorn', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'donut', word: 'Donut', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'hotdog', word: 'Hot Dog', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'french_fries', word: 'French Fries', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'bagel', word: 'Bagel', category: 'food', difficulty: 'easy', language: 'en', clueability: 8, popularity: 8 },
  { id: 'ramen', word: 'Ramen', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'croissant', word: 'Croissant', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'cupcake', word: 'Cupcake', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'honey', word: 'Honey', category: 'food', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'cheese', word: 'Cheese', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'apple', word: 'Apple', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'banana', word: 'Banana', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'strawberry', word: 'Strawberry', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'watermelon', word: 'Watermelon', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'lemon', word: 'Lemon', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'avocado', word: 'Avocado', category: 'food', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'cookie', word: 'Chocolate Cookie', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'smoothie', word: 'Fruit Smoothie', category: 'food', difficulty: 'easy', language: 'en', clueability: 8, popularity: 8 },
  { id: 'waffle', word: 'Belgian Waffle', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'muffin', word: 'Blueberry Muffin', category: 'food', difficulty: 'easy', language: 'en', clueability: 8, popularity: 8 },
  { id: 'lasagna', word: 'Lasagna', category: 'food', difficulty: 'medium', language: 'en', clueability: 8, popularity: 8 },
  { id: 'steak', word: 'Grilled Steak', category: 'food', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'egg', word: 'Fried Egg', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'bacon', word: 'Crispy Bacon', category: 'food', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'cereal', word: 'Breakfast Cereal', category: 'food', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'milkshake', word: 'Milkshake', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'ketchup', word: 'Ketchup', category: 'food', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'peanut_butter', word: 'Peanut Butter', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'garlic', word: 'Garlic Bread', category: 'food', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'burrito', word: 'Burrito', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'pretzel', word: 'Pretzel', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'cotton_candy', word: 'Cotton Candy', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'pie', word: 'Apple Pie', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'salad', word: 'Caesar Salad', category: 'food', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'nachos', word: 'Cheese Nachos', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'marshmallow', word: 'Marshmallow', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'soup', word: 'Tomato Soup', category: 'food', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'curry', word: 'Indian Curry', category: 'food', difficulty: 'medium', language: 'en', clueability: 8, popularity: 8 },
  { id: 'lollipop', word: 'Lollipop', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'cheesecake', word: 'Cheesecake', category: 'food', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },

  // --- 2. Everyday Objects (50 words) ---
  { id: 'umbrella', word: 'Umbrella', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'backpack', word: 'Backpack', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'mirror', word: 'Mirror', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'toothbrush', word: 'Toothbrush', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'sunglasses', word: 'Sunglasses', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'flashlight', word: 'Flashlight', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'pillow', word: 'Pillow', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 10 },
  { id: 'blanket', word: 'Warm Blanket', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'alarm_clock', word: 'Alarm Clock', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'scissors', word: 'Scissors', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'keys', word: 'Keyring', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 10 },
  { id: 'wallet', word: 'Wallet', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 10 },
  { id: 'candle', word: 'Scented Candle', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'soap', word: 'Bar of Soap', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'towel', word: 'Beach Towel', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'shoes', word: 'Running Sneakers', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 10 },
  { id: 'socks', word: 'Wool Socks', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'jacket', word: 'Winter Coat', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'hat', word: 'Baseball Cap', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'gloves', word: 'Winter Gloves', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'comb', word: 'Hair Comb', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'perfume', word: 'Perfume Bottle', category: 'everyday', difficulty: 'medium', language: 'en', clueability: 8, popularity: 8 },
  { id: 'notebook', word: 'Spiral Notebook', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'pen', word: 'Ballpoint Pen', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 10 },
  { id: 'guitar', word: 'Acoustic Guitar', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'bicycle', word: 'Bicycle', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'skateboard', word: 'Skateboard', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'ball', word: 'Soccer Ball', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'mug', word: 'Coffee Mug', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 10 },
  { id: 'plate', word: 'Dinner Plate', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'fork', word: 'Metal Fork', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'bucket', word: 'Water Bucket', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 8 },
  { id: 'broom', word: 'Broomstick', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'trash_can', word: 'Trash Can', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'doorbell', word: 'Doorbell', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'refrigerator', word: 'Refrigerator', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'microwave', word: 'Microwave', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'toaster', word: 'Bread Toaster', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'vacuum', word: 'Vacuum Cleaner', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'lamp', word: 'Desk Lamp', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'calendar', word: 'Wall Calendar', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'tape', word: 'Duct Tape', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 8 },
  { id: 'hammer', word: 'Claw Hammer', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'bandage', word: 'Band-Aid', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'sponge', word: 'Kitchen Sponge', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'stamp', word: 'Postage Stamp', category: 'everyday', difficulty: 'medium', language: 'en', clueability: 8, popularity: 8 },
  { id: 'envelope', word: 'Mailing Envelope', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'suitcase', word: 'Travel Suitcase', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'hanger', word: 'Clothes Hanger', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 8 },
  { id: 'curtain', word: 'Window Curtain', category: 'everyday', difficulty: 'easy', language: 'en', clueability: 8, popularity: 8 },

  // --- 3. Animals & Nature (40 words) ---
  { id: 'penguin', word: 'Penguin', category: 'animals', difficulty: 'easy', language: 'en', clueability: 10, popularity: 10 },
  { id: 'giraffe', word: 'Giraffe', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'dolphin', word: 'Dolphin', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'kangaroo', word: 'Kangaroo', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'octopus', word: 'Octopus', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'volcano', word: 'Volcano', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'lion', word: 'Lion', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'elephant', word: 'Elephant', category: 'animals', difficulty: 'easy', language: 'en', clueability: 10, popularity: 10 },
  { id: 'panda', word: 'Giant Panda', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'tiger', word: 'Bengal Tiger', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'koala', word: 'Koala', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'zebra', word: 'Zebra', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'polar_bear', word: 'Polar Bear', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'monkey', word: 'Monkey', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'owl', word: 'Barn Owl', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'bat', word: 'Cave Bat', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'camel', word: 'Desert Camel', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'flamingo', word: 'Pink Flamingo', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'chameleon', word: 'Chameleon', category: 'animals', difficulty: 'medium', language: 'en', clueability: 9, popularity: 8 },
  { id: 'shark', word: 'Great White Shark', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'whale', word: 'Blue Whale', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'peacock', word: 'Peacock', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 8 },
  { id: 'cheetah', word: 'Cheetah', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'gorilla', word: 'Silverback Gorilla', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'hedgehog', word: 'Hedgehog', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'sloth', word: 'Tree Sloth', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'crocodile', word: 'Crocodile', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'snake', word: 'Rattlesnake', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'bee', word: 'Honeybee', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'butterfly', word: 'Monarch Butterfly', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'parrot', word: 'Talking Parrot', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'eagle', word: 'Bald Eagle', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'rainbow', word: 'Rainbow', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'lightning', word: 'Lightning Storm', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'waterfall', word: 'Waterfall', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'canyon', word: 'Grand Canyon', category: 'animals', difficulty: 'medium', language: 'en', clueability: 8, popularity: 9 },
  { id: 'iceberg', word: 'Floating Iceberg', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'spider', word: 'Tarantula Spider', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'squid', word: 'Giant Squid', category: 'animals', difficulty: 'medium', language: 'en', clueability: 8, popularity: 8 },
  { id: 'frog', word: 'Tree Frog', category: 'animals', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },

  // --- 4. Places & Travel (40 words) ---
  { id: 'airport', word: 'Airport', category: 'places', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'lighthouse', word: 'Lighthouse', category: 'places', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'amusement_park', word: 'Roller Coaster', category: 'places', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'pyramids', word: 'Pyramids of Giza', category: 'places', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'submarine', word: 'Submarine', category: 'places', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'eiffel_tower', word: 'Eiffel Tower', category: 'places', difficulty: 'easy', language: 'en', clueability: 10, popularity: 10 },
  { id: 'statue_of_liberty', word: 'Statue of Liberty', category: 'places', difficulty: 'easy', language: 'en', clueability: 10, popularity: 10 },
  { id: 'hospital', word: 'Hospital Emergency Room', category: 'places', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'cinema', word: 'Movie Theater', category: 'places', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'library', word: 'Quiet Library', category: 'places', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'hotel', word: 'Luxury Hotel', category: 'places', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'beach', word: 'Tropical Beach', category: 'places', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'desert', word: 'Sahara Desert', category: 'places', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'castle', word: 'Medieval Castle', category: 'places', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'prison', word: 'Prison Cell', category: 'places', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'zoo', word: 'City Zoo', category: 'places', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'stadium', word: 'Sports Stadium', category: 'places', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'museum', word: 'Art Museum', category: 'places', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'supermarket', word: 'Supermarket', category: 'places', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'farm', word: 'Dairy Farm', category: 'places', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'space_station', word: 'Space Station', category: 'places', difficulty: 'medium', language: 'en', clueability: 9, popularity: 8 },
  { id: 'cruise_ship', word: 'Cruise Ship', category: 'places', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'bakery', word: 'Fresh Bakery', category: 'places', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'fire_station', word: 'Fire Station', category: 'places', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'gym', word: 'Fitness Gym', category: 'places', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'campsite', word: 'Forest Campsite', category: 'places', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'igloo', word: 'Snow Igloo', category: 'places', difficulty: 'easy', language: 'en', clueability: 9, popularity: 8 },
  { id: 'train_station', word: 'Train Station', category: 'places', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'casino', word: 'Las Vegas Casino', category: 'places', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'waterpark', word: 'Waterpark Waterslide', category: 'places', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'dentist', word: 'Dentist Office', category: 'places', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'aquarium', word: 'Public Aquarium', category: 'places', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'colosseum', word: 'Roman Colosseum', category: 'places', difficulty: 'medium', language: 'en', clueability: 9, popularity: 8 },
  { id: 'bridge', word: 'Golden Gate Bridge', category: 'places', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'mount_everest', word: 'Mount Everest', category: 'places', difficulty: 'medium', language: 'en', clueability: 9, popularity: 9 },
  { id: 'cave', word: 'Dark Cave', category: 'places', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'island', word: 'Desert Island', category: 'places', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'jungle', word: 'Amazon Rainforest', category: 'places', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'restaurant', word: 'Fancy Restaurant', category: 'places', difficulty: 'easy', language: 'en', clueability: 8, popularity: 10 },
  { id: 'playground', word: 'School Playground', category: 'places', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },

  // --- 5. Movies & Pop Culture (40 words) ---
  { id: 'superhero', word: 'Superhero', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'spaceship', word: 'Spaceship', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'vampire', word: 'Vampire', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'pirate_ship', word: 'Pirate Ship', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'wizard', word: 'Hogwarts Wizard', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'alien', word: 'Extraterrestrial Alien', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'zombie', word: 'Walking Zombie', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'dinosaur', word: 'T-Rex Dinosaur', category: 'movies', difficulty: 'easy', language: 'en', clueability: 10, popularity: 10 },
  { id: 'detective', word: 'Sherlock Detective', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'ninja', word: 'Shadow Ninja', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'cowboy', word: 'Wild West Cowboy', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'knight', word: 'Medieval Knight', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'ghost', word: 'Spooky Ghost', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'dragon', word: 'Fire Breathing Dragon', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'mermaid', word: 'Ocean Mermaid', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'secret_agent', word: 'James Bond Spy', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'time_machine', word: 'Time Machine', category: 'movies', difficulty: 'medium', language: 'en', clueability: 9, popularity: 9 },
  { id: 'lightsaber', word: 'Jedi Lightsaber', category: 'movies', difficulty: 'easy', language: 'en', clueability: 10, popularity: 9 },
  { id: 'treasure_chest', word: 'Treasure Chest', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'magic_carpet', word: 'Flying Magic Carpet', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 8 },
  { id: 'frankenstein', word: 'Frankenstein Monster', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'mummy', word: 'Egyptian Mummy', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'robot', word: 'Futuristic Robot', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'gladiator', word: 'Roman Gladiator', category: 'movies', difficulty: 'medium', language: 'en', clueability: 9, popularity: 8 },
  { id: 'samurai', word: 'Japanese Samurai', category: 'movies', difficulty: 'medium', language: 'en', clueability: 9, popularity: 8 },
  { id: 'werewolf', word: 'Full Moon Werewolf', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'fairy', word: 'Winged Tooth Fairy', category: 'movies', difficulty: 'easy', language: 'en', clueability: 8, popularity: 8 },
  { id: 'genie', word: 'Magic Lamp Genie', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'supervillain', word: 'Evil Supervillain', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'invisible_cloak', word: 'Invisibility Cloak', category: 'movies', difficulty: 'medium', language: 'en', clueability: 9, popularity: 8 },
  { id: 'hoverboard', word: 'Flying Hoverboard', category: 'movies', difficulty: 'medium', language: 'en', clueability: 8, popularity: 8 },
  { id: 'cyborg', word: 'Terminator Cyborg', category: 'movies', difficulty: 'medium', language: 'en', clueability: 8, popularity: 8 },
  { id: 'witch', word: 'Witch on a Broom', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'superman_cape', word: 'Red Superhero Cape', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'clown', word: 'Circus Clown', category: 'movies', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'king', word: 'Crown of the King', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'queen', word: 'Royal Queen', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'astronaut', word: 'Apollo Astronaut', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'pirate_eye_patch', word: 'Pirate Eye Patch', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 8 },
  { id: 'olympic_torch', word: 'Olympic Gold Medal', category: 'movies', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },

  // --- 6. Tech & Gadgets (30 words) ---
  { id: 'smartphone', word: 'Smartphone', category: 'tech', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'laptop', word: 'Laptop Computer', category: 'tech', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'headphones', word: 'Over-Ear Headphones', category: 'tech', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'smartwatch', word: 'Apple Smartwatch', category: 'tech', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'tablet', word: 'Touchscreen Tablet', category: 'tech', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'drone', word: 'Flying Drone Camera', category: 'tech', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'game_console', word: 'Video Game Console', category: 'tech', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'virtual_reality', word: 'VR Virtual Reality Headset', category: 'tech', difficulty: 'easy', language: 'en', clueability: 9, popularity: 8 },
  { id: 'wireless_earbuds', word: 'Wireless Earbuds', category: 'tech', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'power_bank', word: 'Portable Power Bank', category: 'tech', difficulty: 'easy', language: 'en', clueability: 8, popularity: 8 },
  { id: 'camera', word: 'Digital DSLR Camera', category: 'tech', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'microphone', word: 'Podcast Microphone', category: 'tech', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'bluetooth_speaker', word: 'Bluetooth Speaker', category: 'tech', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'mouse', word: 'Computer Mouse', category: 'tech', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'keyboard', word: 'Mechanical Keyboard', category: 'tech', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'television', word: 'Smart Flat TV', category: 'tech', difficulty: 'easy', language: 'en', clueability: 9, popularity: 10 },
  { id: 'printer', word: 'Color Printer', category: 'tech', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'projector', word: 'Movie Projector', category: 'tech', difficulty: 'medium', language: 'en', clueability: 8, popularity: 8 },
  { id: 'usb_drive', word: 'USB Flash Drive', category: 'tech', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'wifi_router', word: 'WiFi Router', category: 'tech', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'satellite', word: 'Orbiting Satellite', category: 'tech', difficulty: 'medium', language: 'en', clueability: 9, popularity: 8 },
  { id: 'solar_panel', word: 'Rooftop Solar Panel', category: 'tech', difficulty: 'medium', language: 'en', clueability: 8, popularity: 8 },
  { id: 'electric_car', word: 'Tesla Electric Car', category: 'tech', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
  { id: 'smart_speaker', word: 'Amazon Alexa Echo', category: 'tech', difficulty: 'easy', language: 'en', clueability: 8, popularity: 8 },
  { id: 'calculator', word: 'Pocket Calculator', category: 'tech', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'webcam', word: 'HD Webcam', category: 'tech', difficulty: 'easy', language: 'en', clueability: 8, popularity: 9 },
  { id: 'joystick', word: 'Arcade Joystick', category: 'tech', difficulty: 'easy', language: 'en', clueability: 9, popularity: 8 },
  { id: 'thermostat', word: 'Smart Thermostat', category: 'tech', difficulty: 'medium', language: 'en', clueability: 7, popularity: 8 },
  { id: 'lightbulb', word: 'Color Smart Lightbulb', category: 'tech', difficulty: 'easy', language: 'en', clueability: 8, popularity: 8 },
  { id: 'robot_vacuum', word: 'Roomba Robot Vacuum', category: 'tech', difficulty: 'easy', language: 'en', clueability: 9, popularity: 9 },
];
